### ISSUE TITLE
Limit the number that can be introduced in floor field

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#12]
This is an edge case, but better to have it controlled if you agree @mcav. 
Now you can enter whatever number you want and this is how it looks like:
![screenshot_2016-10-21-11-04-58](https://cloud.githubusercontent.com/assets/1897507/19593121/47cf7a9c-977f-11e6-842c-28b31e59261c.png)
![screenshot_2016-10-21-11-05-12](https://cloud.githubusercontent.com/assets/1897507/19593143/628240d6-977f-11e6-9b87-dd3443fee9eb.png)

**Comment by mcav** [comment]
I agree that it should be addressed if this remains the final spec. I saw from UX today that they are considering alternative options for input (radio buttons). I have a feeling we may find more bugs like this that are worth noting but not worth fixing until we have more concrete UX specs, so I've created a label called "awaiting-ux-spec". When the spec begins to firm up, we can go through these tagged issues again and decide if they're worth addressing.

In general, we're in such an early state that I don't want to do work that will end up getting thrown away later. This applies to testing as well -- we should put the infrastructure in place, but I don't want us to dive too far down the testing rabbit hole until we're farther along as a project. Otherwise we're going to spend a lot of time rewriting tests and code unnecessarily.

**Comment by isabelrios** [comment]
Yeah, you are totally right. I saw UX specs and there are major changes. It is better to wait to have the final specs than working on issues that may change.
I will not open more issues like this. Only major things that could impact at the end.
And about testing, as you said, it is the same. We would need travis to check the app builds after adding changes but not dive into more detailed tests yet.
