### ISSUE TITLE
WiFi screen does not show any wifi to select

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#2]
This is happening both in android and iOS with latest master build. The devices are connected to a WiFi and there are more around to be discovered.

Please see video with the issue seen:
https://youtu.be/j9szTkgfnD8

Maybe it is to early to open an issue about that but thought it was worthy to mention.

**Comment by isabelrios** [comment]
I realized I was getting this error when running cordova run android --DeviceName:

Failed to restore plugin "com.pylonproducts.wifiwizard" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin com.pylonproducts.wifiwizard@~0.2.11 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.pylonproducts.wifiwizard

I had to add the following to confix.xml:
"plugin name="wifiwizard" value="com.pylonproducts.wifiwizard.WifiWizard"

And create this file into www: 
https://github.com/hoerresb/WifiWizard/blob/master/www/WifiWizard.js

I also had to create the www folder manually.

After doing that I get correctly my network, and the list of networks. 
But seems that there is some work to be done manually after cloning the repo and installing everything to get the app working, are we missing some dependencies or it has to be done this way @mcav ?

Thanks!

**Comment by mcav** [comment]
I [updated](https://github.com/mozilla-sensorweb/sensorweb-client/commit/5cfd45f148794818c5eb0125badfca7a896ced9b) the plugin's XML to point to the correct location.

The `www` folder was missing because our build instructions were missing one more step -- you need to run `npm run build` to generate the `www` folder. I'll add that to the README.

With these commits, it should all work again. I tested on a fresh install; please reopen if that doesn't resolve the issue for you as well.
