### ISSUE TITLE
Compass: Make manual selection dialog non-modal

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-client#9]
STR:
On _Where is your sensor screen_ tap on _Next_
The _Select Direction_ menu pops up directly without any user interaction. 

Expected:
As happens in Android, that menu should appear once user pesses on _manually enter your direction_ option

**Comment by mcav** [comment]
I'm unable to produce this one on my phone, but I know why that's happening -- it pops up automatically when there's a problem getting the compass reading. Which iPhone are you using?

**Comment by isabelrios** [comment]
I am using an iPod Touch with iOS 10.0.2

**Comment by mcav** [comment]
Upon further investigation, the problem here is that iPod Touch devices do not have a compass, so the manual selection is the only way to properly input the direction.

The action here, then, is to improve the flow so that it's more obvious what's going on -- i.e. don't put the "manual selection" box behind a half-black overlay, and instead present it as a normal part of the flow.

**Comment by mcav** [comment]
Note: The "Samsung Galaxy J7" also does not have a compass.
